#!/bin/bash

export UCHIWA_STATS=${UCHIWA_STATS:-10}
export UCHIWA_REFRESH=${UCHIWA_REFRESH:-10000}
export UCHIWA_USER=${UCHIWA_USER:-}
export UCHIWA_PASS=${UCHIWA_PASS:-}

/src/uchiwa_binary -c /config/config.json
